services:
  nginx:
    container_name: nginx
    image: "nginx:1.24.0-alpine"
    ports:
      - "80:80"
    entrypoint:
      - nginx-debug 
      - -g 
      - "daemon off;"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
